# Generated by Django 2.1.7 on 2019-03-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190329_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=1, upload_to='postsImage/'),
            preserve_default=False,
        ),
    ]
