# Generated by Django 2.1.7 on 2019-03-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePasswordToken',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=200)),
            ],
        ),
    ]
