# Generated by Django 2.1.7 on 2019-03-27 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePasswordToken',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='', verbose_name='Profile Image')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('number', models.CharField(max_length=16, verbose_name='Phone number')),
                ('bio', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
