# Generated by Django 2.1.7 on 2019-03-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuser',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profile Image'),
        ),
    ]
