# Generated by Django 2.1.7 on 2019-03-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190329_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuser',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='usersProfile/', verbose_name='Profile Image'),
        ),
    ]
